version: '3.1'

services:
  mysql:
    image: mysql
    restart: always
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - trabalho_sd
    environment:
      MYSQL_DATABASE: trabalho_sd
      MYSQL_ROOT_PASSWORD: Smoke123
    ports:
      - 3306:3307
  app:
    image: cactusbank
    restart: always
    build: .
    container_name: app
    depends_on:
      - mysql
    networks:
      - trabalho_sd
    ports:
    - 8080:8080
networks:
  trabalho_sd:
    name: trabalho_sd
    driver: bridge
    external: false
    ipam:
      config:
        - subnet: '172.26.0.0/16'
          gateway: '172.26.0.1'